name: CrisenApp
options:
  bundleIdPrefix: crisen
  deploymentTarget:
    iOS: '18.5'
    watchOS: '11.5'

settings:
  base:
    SWIFT_VERSION: 5.0

targets:
  CrisenApp:
    type: application
    platform: iOS
    sources: [CrisenApp]
    resources: [CrisenApp/Resources]
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: crisen.crisenapp
      INFOPLIST_FILE: CrisenApp/Resources/Info.plist

  CrisenWatchApp:
    type: application
    platform: watchOS
    sources: [CrisenWatchApp]
    resources: [CrisenWatchApp/Resources]
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: crisen.crisenapp.watchapp
      INFOPLIST_FILE: CrisenWatchApp/Resources/Info.plist